apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: repimage-cert
  namespace: kube-system
spec:
  secretName: repimage-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  subject:
    organizations:
      - repimage
  commonName: repimage.kube-system.svc
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - repimage.kube-system.svc
    - repimage.kube-system.svc.cluster.local
  issuerRef:
    name: repimage-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: repimage-selfsigned-issuer
  namespace: kube-system
spec:
  selfSigned: {}
