apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: repimage
  namespace: kube-system
  labels:
    app: repimage
  annotations:
    cert-manager.io/inject-ca-from: kube-system/repimage-cert
webhooks:
- admissionReviewVersions:
  - v1
  - v1bate1
  clientConfig:
    service:
      name: repimage
      namespace: kube-system
      path: /pods
  failurePolicy: Ignore
  name: repimage.kube-system.svc
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: NoneOnDryRun
